export const trainingAreaData = [
    { label: 'Alergia e Imunologia', value: 'CRM' },
    { label: 'Anestesiologia', value: 'CRM' },
    { label: 'Angiologia', value: 'CRM' },
    { label: 'Avaliação Psicológica', value: 'CRP' },
    { label: 'Cardiologia', value: 'CRM' },
    { label: 'Cirurgia Geral', value: 'CRM' },
    { label: 'Cirurgia Pediátrica', value: 'CRM' },
    { label: 'Clínica Médica', value: 'CRM' },
    { label: 'Dermatologia', value: 'CRM' },
    { label: 'Genética Médica', value: 'CRM' },
    { label: 'Geriatria', value: 'CRM' },
    { label: 'Ginecologia e Obstetrícia', value: 'CRM' },
    { label: 'Infectologia', value: 'CRM' },
    { label: 'Mastologia', value: 'CRM' },
    { label: 'Medicina de Emergência', value: 'CRM' },
    { label: 'Medicina de Família e Comunidade', value: 'CRM' },
    { label: 'Medicina Física e Reabilitação', value: 'CRM' },
    { label: 'Neuropsicologia', value: 'CRP' },
    { label: 'Neurologia', value: 'CRM' },
    { label: 'Nutrologia', value: 'CRM' },
    { label: 'Ortopedia e Traumatologia', value: 'CRM' },
    { label: 'Psicologia Clínica', value: 'CRP' },
    { label: 'Psicologia Escolar e Educacional', value: 'CRP' },
    { label: 'Psicologia Hospitalar', value: 'CRP' },
    { label: 'Psicologia em Saúde', value: 'CRP' },
    { label: 'Psicologia Organizacional e do Trabalho', value: 'CRP' },
    { label: 'Psicologia Social', value: 'CRP' },
    { label: 'Psiquiatria', value: 'CRM' },
    { label: 'Radiologia e Diagnóstico por Imagem', value: 'CRM' },
    { label: 'Radioterapia', value: 'CRM' },
    { label: 'Urologia', value: 'CRM' }
]

export const ufData = [
    { label: 'Acre (AC)', value: 'AC' },
    { label: 'Alagoas (AL)', value: 'AL' },
    { label: 'Amapá (AP)', value: 'AP' },
    { label: 'Amazonas (AM)', value: 'AM' },
    { label: 'Bahia (BA)', value: 'BA' },
    { label: 'Ceará (CE)', value: 'CE' },
    { label: 'Distrito Federal (DF)', value: 'DF' },
    { label: 'Espírito Santo (ES)', value: 'ES' },
    { label: 'Goiás (GO)', value: 'GO' },
    { label: 'Maranhão (MA)', value: 'MA' },
    { label: 'Mato Grosso (MT)', value: 'MT' },
    { label: 'Mato Grosso do Sul (MS)', value: 'MS' },
    { label: 'Minas Gerais (MG)', value: 'MG' },
    { label: 'Pará (PA)', value: 'PA' },
    { label: 'Paraíba (PB)', value: 'PB' },
    { label: 'Paraná (PR)', value: 'PR' },
    { label: 'Pernambuco (PE)', value: 'PE' },
    { label: 'Piauí (PI)', value: 'PI' },
    { label: 'Rio de Janeiro (RJ)', value: 'RJ' },
    { label: 'Rio Grande do Norte (RN)', value: 'RN' },
    { label: 'Rio Grande do Sul (RS)', value: 'RS' },
    { label: 'Rondônia (RO)', value: 'RO' },
    { label: 'Roraima (RR)', value: 'RR' },
    { label: 'Santa Catarina (SC)', value: 'SC' },
    { label: 'São Paulo (SP)', value: 'SP' },
    { label: 'Sergipe (SE)', value: 'SE' },
    { label: 'Tocantins (TO)', value: 'TO' }
]